# This file was generated by GoReleaser. DO NOT EDIT.
cask "fisk-ai" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "a6f2356b6f60c99768ebddb4114381ca929ce3cda983d04472ed1e58ad34ce69"
      url "https://github.com/choria-io/fisk-ai/releases/download/v#{version}/fisk-ai-#{version}-darwin-amd64.tar.gz"
      rename "fisk-ai-0.0.1-darwin-amd64/fisk-ai", "fisk-ai"
    end
    on_arm do
      sha256 "63338bba0d5cdeda99b9611a6d45af8afd03b2480cf1920d8de47ab6f0b8ab1e"
      url "https://github.com/choria-io/fisk-ai/releases/download/v#{version}/fisk-ai-#{version}-darwin-arm64.tar.gz"
      rename "fisk-ai-0.0.1-darwin-arm64/fisk-ai", "fisk-ai"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f4eed209c32bf75511b79b0ea143247982cb9368f7464b3196c79e426c54cd1"
      url "https://github.com/choria-io/fisk-ai/releases/download/v#{version}/fisk-ai-#{version}-linux-amd64.tar.gz"
      rename "fisk-ai-0.0.1-linux-amd64/fisk-ai", "fisk-ai"
    end
    on_arm do
      sha256 "b4dcab121120523c425e793bc2009f976ed4b24d7438c94c734ffbcaa90c40ab"
      url "https://github.com/choria-io/fisk-ai/releases/download/v#{version}/fisk-ai-#{version}-linux-arm64.tar.gz"
      rename "fisk-ai-0.0.1-linux-arm64/fisk-ai", "fisk-ai"
    end
  end

  name "fisk-ai"
  desc "Fisk Agent and MCP Creation Toolkit"
  homepage "https://github.com/choria-io/fisk-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fisk-ai"

  # No zap stanza required

end
