# This file was generated by GoReleaser. DO NOT EDIT.
cask "fisk-ai" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "4fcfb7de668959ca560bd493558656b36e0a1069ac4bbfb9890237e321ec925d"
      url "https://github.com/choria-io/fisk-ai/releases/download/v#{version}/fisk-ai-#{version}-darwin-amd64.tar.gz"
      rename "fisk-ai-0.0.2-darwin-amd64/fisk-ai", "fisk-ai"
    end
    on_arm do
      sha256 "df263391ca10b6a7d5e3e69b1d9a243560420987d3b18f253beba5276b9419af"
      url "https://github.com/choria-io/fisk-ai/releases/download/v#{version}/fisk-ai-#{version}-darwin-arm64.tar.gz"
      rename "fisk-ai-0.0.2-darwin-arm64/fisk-ai", "fisk-ai"
    end
  end

  on_linux do
    on_intel do
      sha256 "d18d8cd52ecad0f604488bc630026ad4d252aa6ce80fb8a567f7cf41d6b94022"
      url "https://github.com/choria-io/fisk-ai/releases/download/v#{version}/fisk-ai-#{version}-linux-amd64.tar.gz"
      rename "fisk-ai-0.0.2-linux-amd64/fisk-ai", "fisk-ai"
    end
    on_arm do
      sha256 "4eb09b6d9b15729790a11da70b111f529a849db5a71033c3cd1f0d2902e0f5f3"
      url "https://github.com/choria-io/fisk-ai/releases/download/v#{version}/fisk-ai-#{version}-linux-arm64.tar.gz"
      rename "fisk-ai-0.0.2-linux-arm64/fisk-ai", "fisk-ai"
    end
  end

  name "fisk-ai"
  desc "Fisk Agent and MCP Creation Toolkit"
  homepage "https://github.com/choria-io/fisk-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fisk-ai"

  # No zap stanza required

end
