# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appbuilder < Formula
  desc "Choria Application Builder"
  homepage "https://github.com/choria-io/appbuilder"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/choria-io/appbuilder/releases/download/v0.6.0/appbuilder-0.6.0-darwin-arm64.tar.gz"
      sha256 "7baee18a2d463bac4d1e48d4a4b8b82bf7e3904570050567cb5f5e99b40cce19"

      def install
        bin.install "appbuilder"
        bin.install_symlink "appbuilder" => "abtask"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/choria-io/appbuilder/releases/download/v0.6.0/appbuilder-0.6.0-darwin-amd64.tar.gz"
      sha256 "5aaca834a64d71ee9fddb4f4fae531a33d49e8dfa64d06a2ad7cd53559dbd7fb"

      def install
        bin.install "appbuilder"
        bin.install_symlink "appbuilder" => "abtask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/choria-io/appbuilder/releases/download/v0.6.0/appbuilder-0.6.0-linux-arm6.tar.gz"
      sha256 "77b039da82621434b0f735772d8b7057fdb603427d54bda8ceca05014760f806"

      def install
        bin.install "appbuilder"
        bin.install_symlink "appbuilder" => "abtask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/choria-io/appbuilder/releases/download/v0.6.0/appbuilder-0.6.0-linux-arm64.tar.gz"
      sha256 "c2bb5d54bd11c87013102f042207c4b42c9f249b528350c6eb3a57551e8bec9a"

      def install
        bin.install "appbuilder"
        bin.install_symlink "appbuilder" => "abtask"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/choria-io/appbuilder/releases/download/v0.6.0/appbuilder-0.6.0-linux-amd64.tar.gz"
      sha256 "90e8b5f88077b71f519768ed2f36a6d61b9a3c0e3a761c8cb684ab5713b8a59f"

      def install
        bin.install "appbuilder"
        bin.install_symlink "appbuilder" => "abtask"
      end
    end
  end

  test do
    system "#{bin}/appbuilder --version"
  end
end
