# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appbuilder < Formula
  desc "Choria Application Builder"
  homepage "https://github.com/choria-io/appbuilder"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/choria-io/appbuilder/releases/download/v0.0.5/appbuilder-0.0.5-darwin-arm64.tar.gz"
      sha256 "dd2b39fed63618206c32c951be06b2b373628590d806212e0046fdd03f49e2ee"

      def install
        bin.install "appbuilder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/choria-io/appbuilder/releases/download/v0.0.5/appbuilder-0.0.5-darwin-amd64.tar.gz"
      sha256 "1fd9666eaa51fe60eff2c42f86593057e91549e89d06a393c7ee71d9aa543825"

      def install
        bin.install "appbuilder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/choria-io/appbuilder/releases/download/v0.0.5/appbuilder-0.0.5-linux-arm6.tar.gz"
      sha256 "bf3fbc1214d648012946cdd880e69c85d19ab48b7ecaff7fea68d0d37ccbb33c"

      def install
        bin.install "appbuilder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/choria-io/appbuilder/releases/download/v0.0.5/appbuilder-0.0.5-linux-arm64.tar.gz"
      sha256 "e6adcfe9b0b1a0342e95bc219cadb1f6c28c6f1794b60346a8ad062326d917f5"

      def install
        bin.install "appbuilder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/choria-io/appbuilder/releases/download/v0.0.5/appbuilder-0.0.5-linux-amd64.tar.gz"
      sha256 "02ffaefc5686a17842a00f81373a673b8384c7de2029865f1a6f17ac93f61b15"

      def install
        bin.install "appbuilder"
      end
    end
  end

  test do
    system "#{bin}/appbuilder --version"
  end
end
