# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccm < Formula
  desc "Choria Configuration Management"
  homepage "https://github.com/choria-io/ccm"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/choria-io/ccm/releases/download/v0.0.4/ccm-0.0.4-darwin-amd64.tar.gz"
      sha256 "a458b02ece03baf2964032807e7a2fa9a82382fede046665a449d3aeda22f655"

      def install
        bin.install "ccm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/choria-io/ccm/releases/download/v0.0.4/ccm-0.0.4-darwin-arm64.tar.gz"
      sha256 "0ed25a8951f239aa59562e5346e8c47bfb6e00f83a537f2b2b20f0a06c2d8620"

      def install
        bin.install "ccm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/choria-io/ccm/releases/download/v0.0.4/ccm-0.0.4-linux-amd64.tar.gz"
      sha256 "d96e3c27b5055f097c4da462a898a3b7772de914085ea0272b159b48f27e3905"
      def install
        bin.install "ccm"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/choria-io/ccm/releases/download/v0.0.4/ccm-0.0.4-linux-arm6.tar.gz"
      sha256 "1d6e0fc933c931c5cd685d7c3ad73165ee4136f04fe0e97c250c03fd72e66f9c"
      def install
        bin.install "ccm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/choria-io/ccm/releases/download/v0.0.4/ccm-0.0.4-linux-arm64.tar.gz"
      sha256 "7d4a5c149cb6bee7b13abfb7fd42c1ac5166b6186e758405648547e06b0aedba"
      def install
        bin.install "ccm"
      end
    end
  end

  test do
    system "#{bin}/ccm --version"
  end
end
