# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccm" do
  name "ccm"
  desc "Choria Configuration Management"
  homepage "https://github.com/choria-io/ccm"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccm"

  on_macos do
    on_intel do
      url "https://github.com/choria-io/ccm/releases/download/v#{version}/ccm-#{version}-darwin-amd64.tar.gz"
      sha256 "eeff88bd0df782b8c0d95fc9867ce0a6a765343df0c3ff3befabd11f1cd7570b"
    end
    on_arm do
      url "https://github.com/choria-io/ccm/releases/download/v#{version}/ccm-#{version}-darwin-arm64.tar.gz"
      sha256 "d13d590ca79c47d8ceb8686dd45f146db017528b308f4438a7dd81fa2cf6623b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/choria-io/ccm/releases/download/v#{version}/ccm-#{version}-linux-amd64.tar.gz"
      sha256 "f4f9983a08e84284570bf4ce2c58dca123bbc7e5f99e4a884915eddb3a384e22"
    end
    on_arm do
      url "https://github.com/choria-io/ccm/releases/download/v#{version}/ccm-#{version}-linux-arm64.tar.gz"
      sha256 "84d2eada2e5b000ee3e1a5ab00b18b0fbea98c21c1cb6b7d9d820b4aeeb5a2ca"
    end
  end

  # No zap stanza required
end
