# This file was generated by GoReleaser. DO NOT EDIT.
cask "scaffold" do
  name "scaffold"
  desc "File scaffolding and interactive forms generator"
  homepage "https://github.com/choria-io/scaffold"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scaffold"

  on_macos do
    on_intel do
      url "https://github.com/choria-io/scaffold/releases/download/v#{version}/scaffold-#{version}-darwin-amd64.tar.gz"
      sha256 "9f870ff15d2fc45080f6edf97c5d00243bc7e1dfe9f90c52e1788b4e913d94a6"
      rename "scaffold-0.0.9-darwin-amd64/scaffold", "scaffold"
    end
    on_arm do
      url "https://github.com/choria-io/scaffold/releases/download/v#{version}/scaffold-#{version}-darwin-arm64.tar.gz"
      sha256 "fe5cf68895d7f9d22d2e6f6b055721059226e56d9477eb229cfe467b15732590"
      rename "scaffold-0.0.9-darwin-arm64/scaffold", "scaffold"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/choria-io/scaffold/releases/download/v#{version}/scaffold-#{version}-linux-amd64.tar.gz"
      sha256 "c46def22c4eecd536dfa88e9c956c5c623ef18aa7849a84b20ffa0cb042a20eb"
      rename "scaffold-0.0.9-linux-amd64/scaffold", "scaffold"
    end
    on_arm do
      url "https://github.com/choria-io/scaffold/releases/download/v#{version}/scaffold-#{version}-linux-arm64.tar.gz"
      sha256 "8f1edcf12bf905bcadbf0ca192f29cdeff926aae2496ed1aa55755f12ca24974"
      rename "scaffold-0.0.9-linux-arm64/scaffold", "scaffold"
    end
  end

  # No zap stanza required
end
