# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tinyhiera < Formula
  desc "Choria Tiny Hiera CLI"
  homepage "https://github.com/choria-io/tinyhiera"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/choria-io/tinyhiera/releases/download/v0.0.5/tinyhiera-0.0.5-darwin-amd64.tar.gz"
      sha256 "e0a9ffe3c126181b6757774b3ac6c2b6fbb81d29e9e271653f505a4f21c2fb22"

      def install
        bin.install "tinyhiera"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/choria-io/tinyhiera/releases/download/v0.0.5/tinyhiera-0.0.5-darwin-arm64.tar.gz"
      sha256 "1c6b3e735c988e91aaa54763ef98552719f0b1f310a7527fd32f11259e59ae33"

      def install
        bin.install "tinyhiera"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/choria-io/tinyhiera/releases/download/v0.0.5/tinyhiera-0.0.5-linux-amd64.tar.gz"
      sha256 "cae5db26e69ee3f04edf87dd01526efa6cec2f6d210041731fcbd8df0a044710"
      def install
        bin.install "tinyhiera"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/choria-io/tinyhiera/releases/download/v0.0.5/tinyhiera-0.0.5-linux-arm6.tar.gz"
      sha256 "35d8c91bacbe65e043d5f803b4be1911315fcdb8258091161a0d35e401208f22"
      def install
        bin.install "tinyhiera"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/choria-io/tinyhiera/releases/download/v0.0.5/tinyhiera-0.0.5-linux-arm64.tar.gz"
      sha256 "ef393ad67640cb88f20925f5a021fdf87028a358ccd9a4781f45054bc5dfc63d"
      def install
        bin.install "tinyhiera"
      end
    end
  end

  test do
    system "#{bin}/tinyhiera --version"
  end
end
