# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tinyhiera < Formula
  desc "Choria Tiny Hiera CLI"
  homepage "https://github.com/choria-io/tinyhiera"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/choria-io/tinyhiera/releases/download/v0.0.4/tinyhiera-0.0.4-darwin-amd64.tar.gz"
      sha256 "ad76ca8f879c1cfc3135d906c238779a07df5b73f5f148a08a8687a7ea903e44"

      def install
        bin.install "tinyhiera"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/choria-io/tinyhiera/releases/download/v0.0.4/tinyhiera-0.0.4-darwin-arm64.tar.gz"
      sha256 "193bc186685f7992fc40449d9f0d3f5bde7824005a52eec0967b950f2e41f84e"

      def install
        bin.install "tinyhiera"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/choria-io/tinyhiera/releases/download/v0.0.4/tinyhiera-0.0.4-linux-amd64.tar.gz"
        sha256 "a2ea097b5df42c180414be05610e7461f6a67dbaa3471d778817cfb8bf076f4e"

        def install
          bin.install "tinyhiera"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/choria-io/tinyhiera/releases/download/v0.0.4/tinyhiera-0.0.4-linux-arm6.tar.gz"
        sha256 "51c245d353e13886048485acfcef765429337ae245382f1edcf29bc2c5b4fad3"

        def install
          bin.install "tinyhiera"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/choria-io/tinyhiera/releases/download/v0.0.4/tinyhiera-0.0.4-linux-arm64.tar.gz"
        sha256 "e43b4816ab64d69ba19a51a612f113bba5a12731849d7237d3f54becfc25e4f1"

        def install
          bin.install "tinyhiera"
        end
      end
    end
  end

  test do
    system "#{bin}/tinyhiera --version"
  end
end
